### ISSUE TITLE
Caption option

### ISSUE THREAD

**Issue by saxisme** [n33/jquery.poptrox#17]
Hello, 

I am not sure how the caption option should work.
Can I use the `alt` text inside the `<img>` tag?
Like: `<img src="images/1_thumb.jpg" alt="Alt Text" title="Just an image (#1)" />`

Thanks,

**Comment by saxisme** [comment]
Hi, 

Unfortunatly it didn't solve the problem.
This is the page where I'm having problems: http://208.79.234.206/~livingimmobiliar/annunci/rif-101/
The script file is: `lightbox-set.js` if you need to see it.
The site is build in Wordpress. 

I've tried it also on the demo files `demo1.html`

Thanks,

**Comment by n33** [comment]
You're currently using v2.4.. Try upgrading to the latest version (v2.5.0).

**Comment by saxisme** [comment]
Perfect! Solved.
Thanks.
