### ISSUE TITLE
Caption problem?

### ISSUE THREAD

**Issue by filipkom** [n33/jquery.poptrox#19]
Hi,

I have a question - is there a possibility to make a caption longer? I need to enter description, some links in image caption and I think it's impossible to do it only in "title" section. 

Thanks in advance and sorry for my poor english ;-)

best regards,
filip

**Comment by n33** [comment]
Try doing something like this for each thumbnail:

```html
<a href="/path/to/image.jpg">
  <img src="/path/to/thumbnail.jpg" />
  <p class="description">Put all your stuff here.</p>
</a>
```

Then in your Poptrox config:

```js
caption: { selector: ".description", remove: true }
```

**Comment by Isk1n** [comment]
Still there is a problem with links in captions (which may be helpful for attribution). Nested anchors are illegal. Possible solution is to place anchor and it's caption into some container

**Comment by tszdabee** [comment]
> Still there is a problem with links in captions (which may be helpful for attribution). Nested anchors are illegal. Possible solution is to place anchor and it's caption into some container

Can confirm, linking in captions is still a problem.
