### ISSUE TITLE
When you click again on the image, the lightbox doesn't show the image.

### ISSUE THREAD

**Issue by mauriciovater** [n33/jquery.poptrox#24]
Hello,

the plugin works perfect except for one important thing: first, you click on one image, then close it. When you click again on that image, the image doesn't appear (only the loading image).

Could you tell me where is the problem?

Tested local and online, and with your Demo, on Chrome Browser under W7.

Thanks a lot.

Mauricio

**Comment by HugoGon** [comment]
Hi!

Had the same problem, and it appears to be the src that remains the same sao nothing happens.

so under the function: 
.on('poptrox_reset', function() {

add this line:
$x.attr('src', '');

and it does the trick.
Hope it helps

Cheers

**Comment by mauriciovater** [comment]
Cool!

I'll give a chance again. Thanks your time and your help HugoGon!

**Comment by mauriciovater** [comment]
It works perfectly!

Will you insert this line on the code or that is a task to other people?

(sorry it's my first time here!)

**Comment by n33** [comment]
Looks like a bug, but thanks @HugoGon for a fix. I'll work it into the next version after I test it.

**Comment by HugoGon** [comment]
Great to hear that! Keep up the good work.

Cheers
Hugo
