### ISSUE TITLE
Close Poptrox on button Click (ajax)

### ISSUE THREAD

**Issue by manojgithub3** [n33/jquery.poptrox#28]
How to close Poptrox on button Click (ajax )

**Comment by ajlkn** [comment]
Not sure I follow -- are you asking for a way to close a Poptrox popup via JS?

**Comment by scosist** [comment]
I think this could be related to differences in the `z-index` attributes as I ran into a similar issue. Depending on what `z-index` one has configured for `.poptrox-popup .closer`, the `.closer` may be visible on an image but may not be visible when using ajax (`poptrox-ajax`) and the `z-index` set on `.poptrox-popup .closer` is lower than `baseZIndex`. Of course, this wouldn't indicate a problem with poptrox, rather the configuration being used.
