### ISSUE TITLE
Vimeo video not working on iPhone

### ISSUE THREAD

**Issue by LiSkynden** [n33/jquery.poptrox#29]
I am using PopTrox on this site:
http://boudoir.jirina.fi/
(scroll down to PORTFOLIO and down to last two thumbs) 
video  is not working on iPhone5  iOS8.3 with Safari. It does work on iPhone with Chorme tho, but "crashes" when turning the phone ...  check this video
https://youtu.be/bpywWuyhJt4

I copied the PopTrox Vimeo code from here
https://github.com/n33/jquery.poptrox
and used it like this
< a href="https://vimeo.com/121874333" data-poptrox="vimeo,800x480" class="image fit from-left"><img src="images/thumbs/vidThumb2.jpg" title="kuvateksti" alt="Jirina Alanko Boudoir" /></a>

but i dont think there's anything in that cause the video works on iPhone with Chrome.

Sorry for newbie question but I now noticed i have the  v2.3.2 version ... and the newest is 2.5.1?  Should i download that...?

**Comment by LiSkynden** [comment]
Just to let you know, i changed the index page cause i just couldnt make it work.  Uploaded the page with the non working videos here
http://boudoir.jirina.fi/videoindex.html

**Comment by ajlkn** [comment]
Haven't been able to reproduce this myself, but if it comes up again let me know.
