### ISSUE TITLE
data-poptrox="ignore" jump when gallery is loading

### ISSUE THREAD

**Issue by pekachu** [n33/jquery.poptrox#30]
Hi, if you filter an anchor via "ignore" then when you load del list jump the number of times you use the filter.  ej.:
`<div id="gallery">`
        `<h2><a data-poptrox="ignore" href="#">Skip</h2>`
       `<ul>`
            `<li><a href="path/to/image1.jpg"><img src="path/to/image1_thumbnail.jpg" /></a></li>`
           `<li><a href="path/to/image2.jpg"><img src="path/to/image2_thumbnail.jpg" /></a></li>`
        `</ul>`
`</div>`
then when you click on image1.jpg will show you image2.jpg and so on...
There is a way to fix this.

**Comment by ajlkn** [comment]
There's no image in that first anchor so that's likely what's throwing it off. Try setting the `selector` option to `ul li a` so it only targets the anchors inside your list.
