### ISSUE TITLE
Make caption clickable

### ISSUE THREAD

**Issue by siamkreative** [n33/jquery.poptrox#32]
Hey there,

Could you please make the caption clickable? For now, if we add a link or social media button to the caption, the **onClick event closes the modal**.

``` javascript
$('#four').poptrox({
    caption: function ($a) {
        return $a.attr('title') + ' &rarr; <a href="' + $a.attr('data-link') + '">View on 500px</a>';
    }
});
```

Also, if a user decides to copy the caption, he can't. Because selecting the text with the mouse will close the modal.

What do you think @n33 ?

**Comment by ajlkn** [comment]
Hmm, try setting `usePopupEasyClose` to `false`. Does that work?
