### ISSUE TITLE
popup windows sizing

### ISSUE THREAD

**Issue by ericshubbard** [n33/jquery.poptrox#38]
I am trying to set the windows size for some videos that I am showing but for some reason the popupwidth or popup height doesn't seem to be doing anything.  Also I am was trying to remove the white space where the caption is but the popupcaptionheight doesn't seem to be doing anything either.  Is there another place or something that I need to set the size of this window?

**Comment by ajlkn** [comment]
Not sure if this is still an issue, but if it is please reopen it!
